name: Deploy Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PORT: ${{ secrets.PORT || '3001' }}
    
    - name: Build
      run: npm run build
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PORT: ${{ secrets.PORT || '3001' }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Deploy to production
      run: |
        echo "Deploying with environment variables from GitHub Secrets"
        echo "DATABASE_URL is set: ${{ secrets.DATABASE_URL != '' }}"
        echo "PORT is set: ${{ secrets.PORT != '' }}"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PORT: ${{ secrets.PORT || '3001' }}
